export interface RankGuidance {
  rank: number
  title: string
  tier: string
  tierEmoji: string
  tierColor: string
  tierBg: string
  tierBorder: string
  coachFocus: string[]
  sponsorActions: string[]
  nextRankGoal: string | null
}

export const RANK_GUIDANCE: RankGuidance[] = [
  {
    rank: 1,
    title: "New Coach",
    tier: "Getting Started",
    tierEmoji: "🌱",
    tierColor: "#3B82F6",
    tierBg: "#EFF6FF",
    tierBorder: "#93C5FD",
    coachFocus: [
      "Complete your own health transformation first — be a product of the product",
      "Learn the 5&1 Plan and Fuelings inside and out",
      "Share your story with friends and family to find your first 5 clients",
      "Attend every team training call and OPTAVIA convention",
    ],
    sponsorActions: [
      "Schedule weekly 1:1 calls to build confidence",
      "Help them craft their personal story and elevator pitch",
      "Walk them through the Health Assessment process",
      "Celebrate every small win — first prospect call, first HA scheduled",
    ],
    nextRankGoal: "Get 3+ active clients to reach Associate Coach",
  },
  {
    rank: 2,
    title: "Associate Coach",
    tier: "Getting Started",
    tierEmoji: "🌱",
    tierColor: "#3B82F6",
    tierBg: "#EFF6FF",
    tierBorder: "#93C5FD",
    coachFocus: [
      "Build to 5 active clients and maintain consistent check-ins",
      "Develop a daily method of operation (DMO) for prospecting",
      "Start posting on social media consistently — at least 3x per week",
      "Learn the compensation plan basics and understand how income grows",
    ],
    sponsorActions: [
      "Review their prospect list and help prioritize warm contacts",
      "Role-play Health Assessment conversations",
      "Introduce them to 3-way calls for closing support",
      "Encourage them to track prospects and clients in their tracker",
    ],
    nextRankGoal: "Grow to 5+ active clients to reach Senior Coach",
  },
  {
    rank: 3,
    title: "Senior Coach",
    tier: "Getting Started",
    tierEmoji: "🌱",
    tierColor: "#3B82F6",
    tierBg: "#EFF6FF",
    tierBorder: "#93C5FD",
    coachFocus: [
      "Maintain 5+ active clients with strong retention",
      "Begin identifying clients who could be future coaches",
      "Build a referral system — ask happy clients for introductions",
      "Start learning the business opportunity presentation",
    ],
    sponsorActions: [
      "Teach them to identify coach potential in their clients",
      "Share the business opportunity talk track",
      "Help them see the path from Senior Coach to Certified",
      "Discuss time management: coaching clients vs. growing the business",
    ],
    nextRankGoal: "Earn certification and build consistent client results",
  },
  {
    rank: 4,
    title: "Certified Coach",
    tier: "Building Momentum",
    tierEmoji: "🔥",
    tierColor: "#F59E0B",
    tierBg: "#FFFBEB",
    tierBorder: "#FCD34D",
    coachFocus: [
      "Deepen coaching skills — personalize support for each client phase",
      "Begin having business opportunity conversations with strong clients",
      "Attend leadership trainings and develop your personal brand",
      "Build a system for consistent client onboarding and follow-up",
    ],
    sponsorActions: [
      "Help them develop a client retention strategy",
      "Practice business opportunity conversations together",
      "Introduce team duplication concepts — teach what's replicable",
      "Set a clear 90-day goal for client growth and first coach recruit",
    ],
    nextRankGoal: "Recruit your first coach and expand client base for Certified Executive",
  },
  {
    rank: 5,
    title: "Certified Executive Coach",
    tier: "Building Momentum",
    tierEmoji: "🔥",
    tierColor: "#F59E0B",
    tierBg: "#FFFBEB",
    tierBorder: "#FCD34D",
    coachFocus: [
      "Recruit and launch your first coach — duplicate your success",
      "Support your new coach through their first 30 days intensively",
      "Build a consistent pipeline of both clients and coach prospects",
      "Study the compensation plan deeply — understand team volume and rank advancement",
    ],
    sponsorActions: [
      "Guide them through their first coach recruitment and launch",
      "Teach the coach launch sequence — first 72 hours, first week, first month",
      "Help them balance client work with coach development",
      "Paint the vision of Manager rank and what it means for their income",
    ],
    nextRankGoal: "Build a team of 3+ active coaches to qualify for Manager",
  },
  {
    rank: 6,
    title: "Manager",
    tier: "Team Building",
    tierEmoji: "🚀",
    tierColor: "#14B8A6",
    tierBg: "#F0FDFA",
    tierBorder: "#5EEAD4",
    coachFocus: [
      "Develop each coach on your team with weekly 1:1 support",
      "Hold team meetings to build culture, recognition, and momentum",
      "Teach your coaches how to recruit — duplication is the key",
      "Focus on developing at least 2 coaches toward their own certification",
    ],
    sponsorActions: [
      "Help them structure effective team calls and recognition",
      "Coach them on leading others — the shift from doing to teaching",
      "Discuss income goals and connect daily actions to rank advancement",
      "Introduce them to leadership resources and advanced trainings",
    ],
    nextRankGoal: "Develop coaches who build their own teams for Senior Manager",
  },
  {
    rank: 7,
    title: "Senior Manager",
    tier: "Team Building",
    tierEmoji: "🚀",
    tierColor: "#14B8A6",
    tierBg: "#F0FDFA",
    tierBorder: "#5EEAD4",
    coachFocus: [
      "Develop depth — help your coaches recruit and launch their own coaches",
      "Identify and invest in your 2-3 strongest leaders on the team",
      "Create a team culture of accountability, recognition, and personal growth",
      "Focus on team volume growth, not just personal clients",
    ],
    sponsorActions: [
      "Teach them to identify and invest in their key leaders",
      "Help them run effective team recognition and training events",
      "Discuss the mindset shift from manager to leader",
      "Connect them with peer leaders for mastermind and support",
    ],
    nextRankGoal: "Build multiple producing coach legs for Executive Manager",
  },
  {
    rank: 8,
    title: "Executive Manager",
    tier: "Team Building",
    tierEmoji: "🚀",
    tierColor: "#14B8A6",
    tierBg: "#F0FDFA",
    tierBorder: "#5EEAD4",
    coachFocus: [
      "Develop 3+ strong coach legs that produce volume independently",
      "Begin thinking organizationally — systems, events, recognition programs",
      "Mentor your managers to become leaders who develop other leaders",
      "Start attending Director-level trainings and events",
    ],
    sponsorActions: [
      "Help them build leadership bench strength on their team",
      "Discuss organizational structure and team culture at scale",
      "Encourage them to develop a signature team training or event",
      "Set a clear path and timeline to Director rank",
    ],
    nextRankGoal: "Achieve required team volume and structure for Director",
  },
  {
    rank: 9,
    title: "Director",
    tier: "Leadership",
    tierEmoji: "⭐",
    tierColor: "#8B5CF6",
    tierBg: "#F5F3FF",
    tierBorder: "#C4B5FD",
    coachFocus: [
      "Develop multiple managers who are on their own path to Director",
      "Build a leadership team that can operate and grow without you daily",
      "Focus on events, recognition, and culture that attracts top talent",
      "Study top leaders in the company — learn from those ahead of you",
    ],
    sponsorActions: [
      "Connect them with other Directors for peer support",
      "Help them develop their managers into future directors",
      "Encourage them to take on mentorship roles in the broader community",
      "Discuss long-term vision, legacy, and impact beyond income",
    ],
    nextRankGoal: "Build multiple Director-qualifying legs for Executive Director",
  },
  {
    rank: 10,
    title: "Executive Director",
    tier: "Leadership",
    tierEmoji: "⭐",
    tierColor: "#8B5CF6",
    tierBg: "#F5F3FF",
    tierBorder: "#C4B5FD",
    coachFocus: [
      "Develop Directors within your organization who can lead independently",
      "Create scalable training systems that reach your entire organization",
      "Focus on leader development — your growth comes from their growth",
      "Represent the brand at events and inspire through your story",
    ],
    sponsorActions: [
      "Support their big-picture strategic planning",
      "Help them navigate team dynamics at scale",
      "Encourage them to build cross-team relationships for collaboration",
      "Celebrate their journey and help them mentor the next generation",
    ],
    nextRankGoal: "Continue developing Director legs for Senior Director",
  },
  {
    rank: 11,
    title: "Senior Director",
    tier: "Leadership",
    tierEmoji: "⭐",
    tierColor: "#8B5CF6",
    tierBg: "#F5F3FF",
    tierBorder: "#C4B5FD",
    coachFocus: [
      "Build a self-sustaining organization with multiple Director-level leaders",
      "Focus on vision casting and culture — your organization mirrors your leadership",
      "Invest in your top performers and help them see what's possible",
      "Develop systems for team communication, training, and recognition at scale",
    ],
    sponsorActions: [
      "Serve as a strategic sounding board for organizational decisions",
      "Connect them with company leadership and top-tier events",
      "Help them plan for Regional Director advancement",
      "Support their personal growth — leadership development, speaking, mentoring",
    ],
    nextRankGoal: "Build the organizational depth required for Regional Director",
  },
  {
    rank: 12,
    title: "Regional Director",
    tier: "Executive",
    tierEmoji: "👑",
    tierColor: "#DC2626",
    tierBg: "#FEF2F2",
    tierBorder: "#FCA5A5",
    coachFocus: [
      "Lead a region-sized organization with multiple strong Director branches",
      "Focus on legacy leadership — developing leaders who develop leaders",
      "Contribute to the broader community through mentorship and events",
      "Maintain personal health transformation as an example for thousands",
    ],
    sponsorActions: [
      "Collaborate as peers on organizational strategy",
      "Support their vision for continued growth and impact",
      "Celebrate their achievements and share their story broadly",
      "Help them navigate challenges unique to large organizations",
    ],
    nextRankGoal: "Continue building organizational breadth for National Director",
  },
  {
    rank: 13,
    title: "National Director",
    tier: "Executive",
    tierEmoji: "👑",
    tierColor: "#DC2626",
    tierBg: "#FEF2F2",
    tierBorder: "#FCA5A5",
    coachFocus: [
      "Lead at the national level — your organization impacts thousands of lives",
      "Develop Regional Directors and build multi-generational leadership depth",
      "Speak at company events and be a visible leader for the entire community",
      "Focus on personal development and staying connected to your 'why'",
    ],
    sponsorActions: [
      "Serve as a strategic partner for high-level decisions",
      "Facilitate connections with company executives and top leaders",
      "Support them in balancing leadership demands with personal life",
      "Help them plan for Presidential Director qualifications",
    ],
    nextRankGoal: "Achieve the volume and structure required for Presidential Director",
  },
  {
    rank: 14,
    title: "Presidential Director",
    tier: "Executive",
    tierEmoji: "👑",
    tierColor: "#DC2626",
    tierBg: "#FEF2F2",
    tierBorder: "#FCA5A5",
    coachFocus: [
      "You are a top leader — focus on legacy, impact, and developing future top leaders",
      "Continue to innovate in how you support and inspire your organization",
      "Be a role model for health transformation, leadership, and community",
      "Mentor leaders across the company, not just within your own organization",
    ],
    sponsorActions: [
      "Celebrate this incredible achievement",
      "Continue to serve as a trusted confidant and strategic partner",
      "Support their broader industry influence and speaking engagements",
      "Help them stay grounded in the mission as they lead at the highest levels",
    ],
    nextRankGoal: "Achieve full integration for Integrated Presidential Director",
  },
  {
    rank: 15,
    title: "Integrated Presidential Director",
    tier: "Executive",
    tierEmoji: "👑",
    tierColor: "#DC2626",
    tierBg: "#FEF2F2",
    tierBorder: "#FCA5A5",
    coachFocus: [
      "You've reached the pinnacle — focus on leaving a lasting legacy",
      "Develop the next generation of Presidential Directors in your organization",
      "Champion the mission of Lifelong Transformation, One Healthy Habit at a Time",
      "Continue growing personally — there is always a next level of impact",
    ],
    sponsorActions: [
      "Honor their journey and the lives they've changed",
      "Partner on vision for the future of their organization",
      "Support them in giving back to the broader coaching community",
      "Continue being available as a trusted partner and friend",
    ],
    nextRankGoal: null,
  },
]

export function getRankGuidance(rank: number): RankGuidance {
  return RANK_GUIDANCE.find(g => g.rank === rank) || RANK_GUIDANCE[0]
}

export function getNextRankTitle(rank: number): string | null {
  if (rank >= 15) return null
  const next = RANK_GUIDANCE.find(g => g.rank === rank + 1)
  return next?.title || null
}
