import type { Module, Recipe } from "./types"

export const modules: Module[] = [
  {
    id: "coach-launch",
    title: "Coach Launch Playbook",
    description: "Essential resources to kickstart your coaching journey and build a strong foundation.",
    category: "Getting Started",
    order: 1,
    forNewCoach: true,
    icon: "🚀",
    resources: [
      {
        id: "launch-1",
        title: "New Coach Welcome Letter",
        type: "doc",
        url: "https://docs.google.com/document/d/1arNc-lNb1zJ2WJ0VS87Dpfre973u-IboIYxQqNUr7Vs/edit?usp=sharing",
      },
      {
        id: "launch-2",
        title: "New Coach Printable Checklist",
        type: "doc",
        url: "https://docs.google.com/document/d/118onAvS-zWGDClUpkSOLEcXhRNnuaCir/edit?usp=sharing&ouid=103643178845055801965&rtpof=true&sd=true",
      },
      {
        id: "launch-3",
        title: "How to Purchase Your Coaching Kit",
        type: "video",
        url: "https://vimeo.com/548985412",
      },
      {
        id: "launch-4",
        title: "How to Prepare for Your Social Media Launch",
        type: "doc",
        url: "https://docs.google.com/document/d/1MmQrsmqenglJr_SenBcBH_qkc4k6mWe_/edit?usp=sharing&ouid=103643178845055801965&rtpof=true&sd=true",
      },
      {
        id: "launch-5",
        title: "How to Work Your Launch Post and Common Mistakes to Avoid",
        type: "doc",
        url: "https://docs.google.com/document/d/11tutR54Y_rDUUWkQupfY8cHN9n_VH-fIQPwnTSnDLnU/edit?usp=sharing",
      },
      {
        id: "launch-6",
        title: "How to Nail the Health Assessment",
        type: "doc",
        url: "https://docs.google.com/document/d/1A8UIEidVXGrz8jeDsqKbrRVPbbpWc3b0/edit?usp=sharing&ouid=103643178845055801965&rtpof=true&sd=true",
      },
      {
        id: "launch-7",
        title: "How to Back Into a Health Assessment: Re-Record This",
        type: "video",
        url: "https://vimeo.com/671134401",
      },
      {
        id: "launch-8",
        title: "Effective Follow Up After a Health Assessment",
        type: "doc",
        url: "https://docs.google.com/document/d/1D-DyRUeV5r4jipqnudUxweh3HGFh_hPD/edit?usp=sharing&ouid=103643178845055801965&rtpof=true&sd=true",
      },
      {
        id: "launch-9",
        title: "Common Objections and How to Address Them",
        type: "doc",
        url: "https://docs.google.com/document/d/1TQPw-pKAllqEz7MZXa3XEsxjN5Jo1T5b/edit?usp=sharing&ouid=103643178845055801965&rtpof=true&sd=true",
      },
      {
        id: "launch-10",
        title: "Week One Posting Guide",
        type: "doc",
        url: "https://docs.google.com/document/d/1DIV9pEZlmqzA8ZIAnCPExQ_KhOedjA38OauiOqtqL5c/edit?usp=sharing",
      },
      {
        id: "launch-11",
        title: "Fast Track to Senior Coach",
        type: "doc",
        url: "https://www.canva.com/design/DAGRyr_F44Y/3_36EEwhi6JmMZfl1ZKAvw/edit?utm_content=DAGRyr_F44Y&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton",
      },
      {
        id: "launch-12",
        title: "30 Day New Coach Self-Evaluation",
        type: "doc",
        url: "https://docs.google.com/document/d/1nOC6erBMIws-SZzQ40TCz5DEvBQpmVLMUCI5V7E_8Ys/edit?usp=sharing",
      },
    ],
  },
  {
    id: "client-month-one",
    title: "Launching a Client & Month One",
    description: "Step-by-step guidance for supporting clients through their critical first month.",
    category: "Client Support",
    order: 2,
    forNewCoach: true,
    icon: "🎯",
    resources: [
      {
        id: "client-1",
        title: "New Client Checklist",
        type: "doc",
        url: "https://docs.google.com/document/d/1c8WqcDJPVmSm6h9Ss2x3V02L0apIemDp/edit?usp=sharing&ouid=103643178845055801965&rtpof=true&sd=true",
      },
      {
        id: "client-2",
        title: "Welcome and 9 Tips Text",
        type: "doc",
        url: "https://docs.google.com/document/d/1x9k469K6XvuQ8rcPdgR3z4i9iXKLxBvSIR_77UuDgpM/edit?usp=sharing",
      },
      {
        id: "client-3",
        title: "5 Success Tips",
        type: "doc",
        url: "https://docs.google.com/document/d/1nss0Lsj1L6jr0X8AEZHZ4cdLOt9vW_SZXokHHLy-r9M/edit?usp=sharing",
      },
      {
        id: "client-4",
        title: "Daily Metabolic Health Text Messages Days 1-10",
        type: "doc",
        url: "https://docs.google.com/document/d/1gtH2fYDKLA6f3sv6-yxFUM8b6rLBqp8jF5R7h4ec6i4/edit?usp=sharing",
      },
      {
        id: "client-5",
        title: "Optional Metabolic Health Text Messages Days 10-31",
        type: "doc",
        url: "https://docs.google.com/document/d/1G9YtI07xIvazS4KZcCkLlB4N_E1axueXVeV4R0Na4Yc/edit?usp=sharing",
      },
      {
        id: "client-6",
        title: "Systems Check Questions",
        type: "doc",
        url: "https://docs.google.com/document/d/1xZJ_afiL_W4YcinCkM6NbNWrH2GqZmRnS1XrB_BRLIM/edit?usp=sharing",
      },
      {
        id: "client-7",
        title: "Detailed Systems Check Video for Clients Who Are Not Losing Well",
        type: "video",
        url: "https://docs.google.com/document/d/1HLqL_l7IELKgjlx5d3SBuXi2xdyBSaawJ5JmcKDoGHM/edit?usp=sharing",
      },
      {
        id: "client-8",
        title: "VIP Call How To",
        type: "doc",
        url: "https://docs.google.com/document/d/1vtYewe5sbVziNTzz3Fk3l3DhRt1x0xTps_hxtYEQk7Q/edit?usp=sharing",
      },
      {
        id: "client-9",
        title: "The Mindset Behind Effective Sponsorship",
        type: "video",
        url: "https://vimeo.com/665762974",
      },
    ],
  },
  {
    id: "client-support",
    title: "Client Support Texts & Videos",
    description: "Ready-to-use communication templates and video resources for effective client support.",
    category: "Client Support",
    order: 3,
    forNewCoach: true,
    icon: "💬",
    resources: [
      {
        id: "support-1",
        title: "Schedule for New Client Communication",
        type: "doc",
        url: "https://docs.google.com/document/d/1iYiwp4tMmlmqFDj8JoG8PNiFbF4ed6yRnMJnRMmzW1g/edit?usp=sharing",
      },
      {
        id: "support-2",
        title: "New Client Videos",
        type: "video",
        url: "https://docs.google.com/document/d/1yfVgcKDiXCP6Og1hopzSBGvI8l0MlQpoGt0hnxjXf_U/edit?usp=sharing",
      },
      {
        id: "support-3",
        title: "Welcome and 9 Tips",
        type: "doc",
        url: "https://docs.google.com/document/d/1x9k469K6XvuQ8rcPdgR3z4i9iXKLxBvSIR_77UuDgpM/edit?usp=sharing",
      },
      {
        id: "support-4",
        title: "Metabolic Health Texts Days 1-9",
        type: "doc",
        url: "https://docs.google.com/document/d/1gtH2fYDKLA6f3sv6-yxFUM8b6rLBqp8jF5R7h4ec6i4/edit?usp=sharing",
      },
      {
        id: "support-5",
        title: "Expanded Metabolic Health Texts Days 10-30",
        type: "doc",
        url: "https://docs.google.com/document/d/1G9YtI07xIvazS4KZcCkLlB4N_E1axueXVeV4R0Na4Yc/edit?usp=sharing",
      },
      {
        id: "support-6",
        title: "Digital Guides",
        type: "doc",
        url: "https://docs.google.com/document/d/1TtZoQcKzTT77PZP0XNlMH-e8HiYzwKhS1UL8ZW5BcT8/edit?usp=sharing",
      },
      {
        id: "support-7",
        title: "Eat This Every Day",
        type: "doc",
        url: "https://docs.google.com/document/d/1_4kgw8X0_bHp6mbGW5Xtwdg0_W7hVYBWwNgHNSM3xLk/edit?usp=sharing",
      },
      {
        id: "support-8",
        title: "How to Update Your Premier Order",
        type: "doc",
        url: "https://docs.google.com/document/d/1D-ueL9kljNxEdqHFrvp9u-aze-z3-2glZaYN-936fCc/edit?usp=sharing",
      },
    ],
  },
  {
    id: "branding",
    title: "Branding Your Business",
    description: "Tools and strategies to create a compelling personal brand that attracts clients.",
    category: "Business Building",
    order: 4,
    forNewCoach: true,
    icon: "✨",
    resources: [
      {
        id: "brand-1",
        title: "How to Add a Disclaimer to Your Pictures",
        type: "video",
        url: "https://www.youtube.com/watch?v=Z4ABPUk5JHs",
      },
      {
        id: "brand-2",
        title: "How to Add a Wellness Credit",
        type: "video",
        url: "https://vimeo.com/473831198",
      },
      {
        id: "brand-3",
        title: "Branding and Setting Up Your Business",
        type: "doc",
        url: "https://docs.google.com/document/d/10aK_KwiHBXsVuUzRS2DjFmly0QH_VJ44ohSIMuxEJ3A/edit?usp=sharing",
      },
      {
        id: "brand-4",
        title: "Setting Up Your Coaching Website",
        type: "video",
        url: "https://youtu.be/xtSR2nJJfAg?si=dHRxhzOE_b1wcIF5",
      },
      {
        id: "brand-5",
        title: "Setting Up Your OPTAVIA Pay",
        type: "doc",
        url: "https://docs.google.com/document/d/1LuGK2ZNo8lFI51vesDKKHdUDCpgKhvtztv3-KS06KvE/edit?usp=sharing",
      },
      {
        id: "brand-6",
        title: "OPTAVIA Vocabulary",
        type: "doc",
        url: "https://docs.google.com/document/d/1jLPNcT5cROxHm8y_XWpCC4AQjnMo9bjwZs-Kz5UVXTY/edit?usp=sharing",
      },
    ],
  },
  {
    id: "social-media",
    title: "Social Media Strategy",
    description: "Proven social media tactics to grow your audience and generate leads.",
    category: "Business Building",
    order: 5,
    forNewCoach: false,
    icon: "📱",
    resources: [
      {
        id: "social-1",
        title: "How to Create a Simple Reel",
        type: "video",
        url: "https://vimeo.com/1147526154",
      },
      {
        id: "social-2",
        title: "How to Have Effective Conversations",
        type: "doc",
        url: "https://www.canva.com/design/DAGwKmV4-qY/jcb8D4BueFoAYZsc8uERiQ/view?utm_content=DAGwKmV4-qY&utm_campaign=designshare&utm_medium=link&utm_source=viewer",
      },
    ],
  },
  {
    id: "coaching-10x",
    title: "Coaching 10X",
    description: "Advanced coaching strategies to scale your business and achieve exponential growth.",
    category: "Training",
    order: 6,
    forNewCoach: false,
    icon: "⚡",
    resources: [
      {
        id: "10x-1",
        title: "10X Kickoff Call",
        type: "video",
        url: "https://vimeo.com/1114863189?fl=tl&fe=ec",
      },
    ],
  },
  {
    id: "metabolic-reset",
    title: "Coaching a Metabolic Reset",
    description: "Comprehensive resources for coaching clients through metabolic health transformation.",
    category: "Training",
    order: 7,
    forNewCoach: false,
    icon: "🔄",
    resources: [
      {
        id: "metabolic-1",
        title: "Metabolic Talking Points for Coaches",
        type: "doc",
        url: "https://docs.google.com/document/d/1GzyY4Je8wWtYxoY7DsuVlPTgCJWdEUzK8jp4UmS6MnQ/edit?usp=sharing",
      },
      {
        id: "metabolic-2",
        title: "10 Questions That Will Help You Gauge Your Metabolic Health",
        type: "video",
        url: "https://vimeo.com/1135751990/8205c4652d?fl=tl&fe=ec",
      },
    ],
  },
  {
    id: "moving-to-ed",
    title: "Moving to ED and Beyond",
    description: "Resources for advancing your coaching practice and expanding your business reach.",
    category: "Training",
    order: 8,
    forNewCoach: false,
    icon: "📈",
    resources: [
      {
        id: "ed-1",
        title: "Moving to ED and Beyond",
        type: "doc",
        url: "https://docs.google.com/document/d/15AyF_jd0KTKYgGyiruHMiZusQ_sDOg7DWXrpkxmAg7I/edit?usp=sharing",
      },
    ],
  },
  {
    id: "connect-business",
    title: "How to Use Connect to Grow Your Business",
    description: "Learn how to leverage OPTAVIA Connect to expand your coaching business and track your growth.",
    category: "Business Building",
    order: 9,
    forNewCoach: false,
    icon: "🔗",
    resources: [
      {
        id: "connect-1",
        title: "Basic How to Check Your Current and Projected FQV",
        type: "video",
        url: "https://www.loom.com/share/799a4ae74a7645aabab8f3d67a4215cf",
      },
      {
        id: "connect-2",
        title: "How to Run Projected Numbers for Yourself and a Team",
        type: "video",
        url: "https://www.loom.com/share/9da0ac3751e84db09ee375c9c039c527",
      },
      {
        id: "connect-3",
        title: "How to End the Month Strategically",
        type: "video",
        url: "https://vimeo.com/1105267713/6d51506452?fl=tl&fe=ec",
      },
    ],
  },
  {
    id: "team-resources",
    title: "Team Resources",
    description: "Essential trackers and tools for managing and growing your coaching team.",
    category: "Business Building",
    order: 10,
    forNewCoach: false,
    icon: "👥",
    resources: [
      {
        id: "team-1",
        title: "Teaching Your Chat GPT to Know You",
        type: "doc",
        url: "https://cdn.fbsbx.com/v/t59.2708-21/600933254_1848441836031561_1534090109953931690_n.pdf/PDF.pdf?_nc_cat=108&ccb=1-7&_nc_sid=2b0e22&_nc_ohc=pwe4VZspIpEQ7kNvwGV9R2-&_nc_oc=AdlX-wH52TdslJupV3jbn-wI8tvNc0Pnn9u5fwUtUcVGx5D9IWQNYKgujqwE7-bbYW29P6w7PzdCgymKzbYYxeJr&_nc_zt=7&_nc_ht=cdn.fbsbx.com&_nc_gid=MuExEBy5Lkhwb-W2_9Mx3Q&oh=03_Q7cD4AGKFuHDjq_XAG-rezLvQKghcg11VyMyou3qrtoeJOFSWA&oe=6940AD9F&dl=1",
      },
      {
        id: "team-2",
        title: "ED Daily Tracker",
        type: "doc",
        url: "https://docs.google.com/document/d/1kCzIHm7DV1WPSTsbTh-NZr4qXj278iZ52vOPs08PfbE/edit",
      },
      {
        id: "team-3",
        title: "FIBC Daily Tracker",
        type: "doc",
        url: "https://docs.google.com/document/d/1WSH2shc6mhmoJubPEdNOwyRC2VPotHOnzvYEBSDx-bk/edit",
      },
      {
        id: "team-4",
        title: "Grow to FIBC Bubble Tracker",
        type: "doc",
        url: "https://docs.google.com/document/d/1xwxMPmRRdBLHsyNLz1rkgMRDK6f8-_gr/edit",
      },
      {
        id: "team-5",
        title: "Global/Presidential Daily Tracker",
        type: "doc",
        url: "https://docs.google.com/document/d/1j9fcAHJ769BRyqaOhZ60HFzb7VhoB0gc3KL5pjyT1PQ/edit",
      },
      {
        id: "team-6",
        title: "IPD Bubble Tracker",
        type: "doc",
        url: "https://docs.google.com/document/d/1JRnQ_uavSfOVj3Mvwf7T2lCASmj8jnEb/edit",
      },
    ],
  },
  {
    id: "gold-standard",
    title: "Gold Standard Trainings",
    description: "Advanced coaching techniques and best practices for experienced coaches.",
    category: "Training",
    order: 11,
    forNewCoach: false,
    icon: "🏆",
    resources: [
      {
        id: "gold-1",
        title: "10X Kickoff Call with Kristen Glass",
        type: "video",
        url: "https://vimeo.com/manage/videos/1115495757/3e666d9fcd",
      },
    ],
  },
]

export const recipes: Recipe[] = [
  {
    id: "recipe-1",
    title: "Grilled Lemon Herb Chicken",
    description: "Juicy grilled chicken breast marinated in fresh lemon and herbs, served with steamed broccoli.",
    image: "/grilled-lemon-herb-chicken-with-broccoli.jpg",
    category: "Chicken",
    prepTime: 15,
    cookTime: 20,
    servings: 1,
    difficulty: "Easy",
    counts: { lean: 1, green: 3, fat: 0, condiment: 1 },
    ingredients: [
      "5-7 oz boneless, skinless chicken breast",
      "2 cups broccoli florets",
      "2 tbsp fresh lemon juice",
      "1 tsp dried oregano",
      "1 tsp garlic powder",
      "Salt and pepper to taste",
      "Cooking spray",
    ],
    instructions: [
      "Combine lemon juice, oregano, garlic powder, salt, and pepper in a bowl.",
      "Add chicken and marinate for at least 10 minutes.",
      "Preheat grill or grill pan to medium-high heat.",
      "Grill chicken for 6-8 minutes per side until fully cooked (internal temp 165°F).",
      "Steam broccoli until tender, about 5-7 minutes.",
      "Serve chicken with broccoli and enjoy!",
    ],
  },
  {
    id: "recipe-2",
    title: "Pan-Seared Salmon with Asparagus",
    description: "Perfectly seared salmon fillet with crispy skin, paired with roasted asparagus.",
    image: "/pan-seared-salmon-with-asparagus.jpg",
    category: "Seafood",
    prepTime: 10,
    cookTime: 15,
    servings: 1,
    difficulty: "Medium",
    counts: { lean: 1, green: 3, fat: 1, condiment: 0 },
    ingredients: [
      "5-7 oz salmon fillet",
      "2 cups asparagus spears",
      "1 tsp olive oil",
      "1 tsp lemon zest",
      "Fresh dill",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Pat salmon dry and season with salt, pepper, and lemon zest.",
      "Heat olive oil in a non-stick pan over medium-high heat.",
      "Place salmon skin-side down and cook for 5-6 minutes without moving.",
      "Flip and cook for another 3-4 minutes until desired doneness.",
      "Roast asparagus at 400°F for 10-12 minutes.",
      "Garnish salmon with fresh dill and serve with asparagus.",
    ],
  },
  {
    id: "recipe-3",
    title: "Beef Stir-Fry with Bell Peppers",
    description: "Tender beef strips stir-fried with colorful bell peppers in a light sauce.",
    image: "/beef-stir-fry-with-bell-peppers.jpg",
    category: "Beef",
    prepTime: 15,
    cookTime: 12,
    servings: 1,
    difficulty: "Medium",
    counts: { lean: 1, green: 3, fat: 0, condiment: 2 },
    ingredients: [
      "5-7 oz lean beef strips",
      "1.5 cups sliced bell peppers (red, yellow, green)",
      "1 cup snap peas",
      "2 tbsp low-sodium soy sauce",
      "1 tsp ginger, minced",
      "2 cloves garlic, minced",
      "Cooking spray",
    ],
    instructions: [
      "Season beef strips with salt and pepper.",
      "Heat a wok or large skillet over high heat and spray with cooking spray.",
      "Stir-fry beef for 3-4 minutes until browned, then remove.",
      "Add peppers and snap peas, stir-fry for 3-4 minutes.",
      "Return beef to pan, add soy sauce, ginger, and garlic.",
      "Toss everything together for 2 minutes and serve hot.",
    ],
  },
  {
    id: "recipe-4",
    title: "Turkey Lettuce Wraps",
    description: "Flavorful ground turkey wrapped in crisp lettuce leaves with Asian-inspired seasonings.",
    image: "/turkey-lettuce-wraps.jpg",
    category: "Turkey",
    prepTime: 10,
    cookTime: 15,
    servings: 1,
    difficulty: "Easy",
    counts: { lean: 1, green: 3, fat: 0, condiment: 1 },
    ingredients: [
      "5-7 oz lean ground turkey",
      "6-8 large lettuce leaves",
      "1 cup diced cucumber",
      "1/2 cup shredded carrots",
      "2 tbsp rice vinegar",
      "1 tsp sesame seeds",
      "Green onions, chopped",
    ],
    instructions: [
      "Cook ground turkey in a skillet over medium heat until browned.",
      "Season with garlic powder, ginger, and a splash of rice vinegar.",
      "Prepare lettuce leaves by washing and patting dry.",
      "Mix cucumber and carrots in a bowl.",
      "Spoon turkey into lettuce leaves.",
      "Top with veggie mixture, sesame seeds, and green onions.",
    ],
  },
  {
    id: "recipe-5",
    title: "Herb-Crusted Pork Tenderloin",
    description: "Tender pork tenderloin with a flavorful herb crust, served with roasted Brussels sprouts.",
    image: "/herb-crusted-pork-tenderloin-brussels-sprouts.jpg",
    category: "Pork",
    prepTime: 15,
    cookTime: 25,
    servings: 1,
    difficulty: "Medium",
    counts: { lean: 1, green: 3, fat: 0, condiment: 1 },
    ingredients: [
      "5-7 oz pork tenderloin",
      "2 cups Brussels sprouts, halved",
      "2 tsp Dijon mustard",
      "1 tsp dried rosemary",
      "1 tsp dried thyme",
      "Salt and pepper",
      "Cooking spray",
    ],
    instructions: [
      "Preheat oven to 400°F.",
      "Rub pork with Dijon mustard, then coat with herbs, salt, and pepper.",
      "Sear pork in an oven-safe skillet for 2 minutes per side.",
      "Transfer skillet to oven and roast for 15-20 minutes.",
      "Toss Brussels sprouts with cooking spray and roast for 20 minutes.",
      "Let pork rest 5 minutes before slicing and serve with Brussels sprouts.",
    ],
  },
  {
    id: "recipe-6",
    title: "Vegetarian Cauliflower Steak",
    description: "Thick-cut cauliflower steaks roasted with herbs and spices, served with a mixed green salad.",
    image: "/roasted-cauliflower-steak-with-salad.jpg",
    category: "Vegetarian",
    prepTime: 10,
    cookTime: 25,
    servings: 1,
    difficulty: "Easy",
    counts: { lean: 0, green: 3, fat: 1, condiment: 1 },
    ingredients: [
      "1 large cauliflower head, cut into steaks",
      "2 cups mixed greens",
      "1 cup cherry tomatoes, halved",
      "1 tsp olive oil",
      "1 tsp smoked paprika",
      "1 tsp cumin",
      "Balsamic vinegar",
    ],
    instructions: [
      "Preheat oven to 425°F.",
      "Brush cauliflower steaks with olive oil.",
      "Season with paprika, cumin, salt, and pepper.",
      "Roast for 20-25 minutes, flipping halfway through.",
      "Toss greens and tomatoes with balsamic vinegar.",
      "Serve cauliflower steak over salad.",
    ],
  },
  {
    id: "recipe-7",
    title: "Breakfast Egg White Scramble",
    description: "Fluffy egg white scramble packed with colorful vegetables for a protein-rich start.",
    image: "/egg-white-scramble-with-vegetables.jpg",
    category: "Breakfast",
    prepTime: 5,
    cookTime: 10,
    servings: 1,
    difficulty: "Easy",
    counts: { lean: 1, green: 3, fat: 0, condiment: 0 },
    ingredients: [
      "1 cup egg whites (or 4-5 egg whites)",
      "1 cup spinach",
      "1/2 cup diced tomatoes",
      "1/2 cup mushrooms, sliced",
      "Salt and pepper",
      "Cooking spray",
    ],
    instructions: [
      "Heat a non-stick pan over medium heat with cooking spray.",
      "Add mushrooms and cook for 2-3 minutes.",
      "Add spinach and tomatoes, cook until spinach wilts.",
      "Pour in egg whites and season with salt and pepper.",
      "Scramble gently until eggs are fully cooked.",
      "Serve immediately.",
    ],
  },
  {
    id: "recipe-8",
    title: "Garlic Shrimp with Zucchini Noodles",
    description: "Succulent garlic shrimp served over fresh zucchini noodles for a light, satisfying meal.",
    image: "/garlic-shrimp-with-zucchini-noodles.jpg",
    category: "Seafood",
    prepTime: 10,
    cookTime: 8,
    servings: 1,
    difficulty: "Easy",
    counts: { lean: 1, green: 3, fat: 0, condiment: 1 },
    ingredients: [
      "5-7 oz shrimp, peeled and deveined",
      "2 medium zucchini, spiralized",
      "3 cloves garlic, minced",
      "1 tbsp lemon juice",
      "Red pepper flakes",
      "Fresh parsley",
      "Cooking spray",
    ],
    instructions: [
      "Heat a large skillet over medium-high heat with cooking spray.",
      "Add shrimp and cook for 2 minutes per side until pink.",
      "Remove shrimp and set aside.",
      "Add garlic to pan and cook for 30 seconds.",
      "Add zucchini noodles and cook for 2-3 minutes.",
      "Return shrimp to pan, add lemon juice, and toss. Garnish with parsley.",
    ],
  },
  {
    id: "recipe-9",
    title: "Chicken Fajita Bowl",
    description: "Seasoned chicken strips with sautéed peppers and onions over fresh greens.",
    image: "/chicken-fajita-bowl-with-peppers.jpg",
    category: "Chicken",
    prepTime: 15,
    cookTime: 15,
    servings: 1,
    difficulty: "Easy",
    counts: { lean: 1, green: 3, fat: 0, condiment: 2 },
    ingredients: [
      "5-7 oz chicken breast, sliced",
      "1 cup bell peppers, sliced",
      "1 cup onions, sliced",
      "1 cup romaine lettuce",
      "2 tsp fajita seasoning",
      "Lime wedges",
      "Cooking spray",
    ],
    instructions: [
      "Season chicken with fajita seasoning.",
      "Heat skillet over medium-high heat with cooking spray.",
      "Cook chicken for 5-6 minutes until fully cooked, then remove.",
      "Add peppers and onions to pan, cook for 5 minutes.",
      "Arrange lettuce in a bowl.",
      "Top with chicken and vegetables, serve with lime wedges.",
    ],
  },
  {
    id: "recipe-10",
    title: "Mediterranean Cod",
    description: "Flaky cod fillet baked with tomatoes, olives, and Mediterranean herbs.",
    image: "/mediterranean-baked-cod-with-tomatoes.jpg",
    category: "Seafood",
    prepTime: 10,
    cookTime: 20,
    servings: 1,
    difficulty: "Easy",
    counts: { lean: 1, green: 3, fat: 0, condiment: 2 },
    ingredients: [
      "5-7 oz cod fillet",
      "1 cup cherry tomatoes",
      "1 cup green beans",
      "5 Kalamata olives, sliced",
      "1 tsp dried oregano",
      "Lemon juice",
      "Cooking spray",
    ],
    instructions: [
      "Preheat oven to 400°F.",
      "Place cod in a baking dish sprayed with cooking spray.",
      "Top with tomatoes, olives, and oregano.",
      "Bake for 15-18 minutes until fish flakes easily.",
      "Steam green beans until tender.",
      "Drizzle fish with lemon juice and serve with green beans.",
    ],
  },
  {
    id: "recipe-11",
    title: "Turkey Meatballs with Marinara",
    description: "Lean turkey meatballs simmered in sugar-free marinara sauce with side salad.",
    image: "/turkey-meatballs-with-marinara-sauce.jpg",
    category: "Turkey",
    prepTime: 15,
    cookTime: 25,
    servings: 1,
    difficulty: "Medium",
    counts: { lean: 1, green: 3, fat: 0, condiment: 2 },
    ingredients: [
      "5-7 oz ground turkey",
      "1 egg white",
      "2 cups marinara sauce (sugar-free)",
      "2 cups mixed greens",
      "1 tsp Italian seasoning",
      "Garlic powder",
      "Cooking spray",
    ],
    instructions: [
      "Preheat oven to 375°F.",
      "Mix turkey, egg white, Italian seasoning, and garlic powder.",
      "Form into 6-8 meatballs and place on baking sheet.",
      "Bake for 20 minutes until cooked through.",
      "Heat marinara sauce in a pan.",
      "Add meatballs to sauce and simmer for 5 minutes. Serve with salad.",
    ],
  },
  {
    id: "recipe-12",
    title: "Spicy Beef Lettuce Cups",
    description: "Spicy seasoned ground beef served in crisp lettuce cups with fresh toppings.",
    image: "/spicy-beef-lettuce-cups.jpg",
    category: "Beef",
    prepTime: 10,
    cookTime: 12,
    servings: 1,
    difficulty: "Easy",
    counts: { lean: 1, green: 3, fat: 0, condiment: 1 },
    ingredients: [
      "5-7 oz lean ground beef",
      "6-8 butter lettuce leaves",
      "1 cup diced tomatoes",
      "1/2 cup diced cucumbers",
      "Chili powder",
      "Cumin",
      "Lime juice",
    ],
    instructions: [
      "Brown ground beef in a skillet over medium heat.",
      "Season with chili powder, cumin, salt, and pepper.",
      "Drain any excess fat.",
      "Prepare lettuce cups and arrange on a plate.",
      "Fill each cup with seasoned beef.",
      "Top with tomatoes and cucumbers, squeeze lime juice over.",
    ],
  },
]
